### ISSUE TITLE
Tracking port crashes if you write address before pressing "+"

### ISSUE THREAD

**Issue by lepmik** [CINPLA/tracking-plugin#10]

**Comment by alejoe91** [comment]
This is probably due to the fact that when writing the address the Tracking Node Editor tries to set the address of the selected source in the processor. The fix should check the length of the available sources and setAddress only when at least one source is created, or when the selectedSources index is != -1

**Comment by alejoe91** [comment]
fixed here 5646f1bf14be9407339a7b6cec722140e2a494b1
